services:
  web:
    build: .
    ports:
      - "2412:2412"
    environment:
      - SECRET_KEY=canhieuxieudeptrynhtthegioi
    volumes:
      - ./instance:/app/instance
      - ./uploads:/app/uploads
